version: '3'
services:

  postgres:
    image: "postgres:9.6-alpine"
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    x-tinkr:
      cpu: 512
      memory: 512
      network:
        public: false  # Indicates this service is accessible in private subnets
      ports:
        postgres-5432:
          port: 5432
          protocol: tcp
          public: false
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban

  app:
    build: ./kanban-app
    container_name: kanban-app
    x-tinkr:
      cpu: 512
      memory: 512
      environment:
        - DB_SERVER=<hostname:postgres-5432>
      network:
        public: true  # Indicates this service is accessible in public subnets
      ports:
        backend-8080:
          port: 8080
          protocol: http
          public: true
          healthcheck:
            timeout: 10
            interval: 30
            path: /
            retries: 3
            success_code: 200-399
    environment:
      - DB_SERVER=postgres
      - POSTGRES_DB=kanban
      - POSTGRES_USER=kanban
      - POSTGRES_PASSWORD=kanban
    ports:
      - 8080:8080
    links:
      - postgres

  kanban-ui:
    build: ./kanban-ui
    container_name: kanban-ui
    x-tinkr:
      cpu: 512
      memory: 512
      network:
        public: true  # Indicates this service is accessible in public subnets
      environment:
        - APP_URL=<url:app:8080>
      ports:
        backend-8080:
          port: 8080
          protocol: http
          public: true
          healthcheck:
            timeout: 10
            interval: 30
            path: /
            retries: 3
            success_code: 200-399
    environment:
      - APP_URL=http://app:8080
    ports:
      - 4200:80
    links:
      - app


volumes:
  kanban-data:
